name: core
description: Shared utilities and core functionality for Camino Ninja.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
