name: PR Check

on:
  pull_request:
    branches:
      - develop
      - 'release/**'
      - 'hotfix/**'
  workflow_dispatch:

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze_and_test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version-file: pubspec.yaml

    - name: Activate melos
      run: dart pub global activate melos 6.3.2

    - name: Create env stubs
      run: |
        touch .env.development
        touch .env.staging
        touch .env.production

    - name: Bootstrap workspace
      run: melos bootstrap

    - name: Analyze
      run: melos run analyze --no-select

    - name: Test
      run: melos run test --no-select
